name: CI/CD for RFM Notebook  # Workflow adı

on:
  push:  # Tetikleyici: Her push'ta çalışır
    branches: [ main ]  # Veya master, senin dalına göre değiştir
  pull_request:
    branches: [ main ]

jobs:
  build:  # İş adı
    runs-on: ubuntu-latest  # Makine: Ubuntu
    steps:
    - uses: actions/checkout@v4  # Repo'yu klonla

    - name: Set up Python 3.13  # Python kur
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies  # Kütüphaneleri yükle
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy matplotlib jupyter kagglehub nbconvert

    - name: Run Notebook  # Notebook'u çalıştır
      run: |
        jupyter nbconvert --to notebook --execute --inplace rfm_with_dataset.ipynb  # Notebook adını kontrol et

    - name: Deploy to GitHub Pages (CD)  # HTML'e dönüştür ve deploy et
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./rfm_with_dataset.html  # HTML'i dönüştür
      if: github.ref == 'refs/heads/main'  # Sadece main dalında
